version: "3.7"
services:
#  api_service:
#    build: .
#    image: assignment11/rd:latest
#    container_name: Assignment11
#    restart: always
#    ports:
#      - 8086:8080
#    networks:
#      - springapipostgres-net
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RDCommerce
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: Ab123456
#    depends_on:
#      - postgres
#    volumes:
#      - .m2:/root/.m2
  #
  #  postgres:
  #    image: "postgres:latest"
  #    restart: always
  #    container_name: postgres-edu
  #    ports:
  #      - 5420:5432
  #    environment:
  #      POSTGRES_PASSWORD: Ab123456
  #      POSTGRES_USER: postgres
  #      POSTGRES_DB: RDCommerce
  #networks:
  #  springapipostgres-net:

  #version: "3.7"
  #services:
  #  api_service:
  #    build: .
  #    image: assignment11/rd:latest
  #    container_name: Assignment11
  #    restart: always
  #    ports:
  #      - 8086:8080
  #    networks:
  #      - springapimysql-net
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/marketplace?useSSL=false&allowPublicKeyRetrieval=true
  #      SPRING_DATASOURCE_USERNAME: admin
  #      SPRING_DATASOURCE_PASSWORD: secret
  #    depends_on:
  #      - mysqldb
  #    volumes:
  #      - .m2:/root/.m2
  #
  ShipmentService-MySQL:
    image: "mysql:8.0"
    restart: always
    container_name: shipmentservice-mysql
    ports:
      - 3312:3306
    environment:
      MYSQL_DATABASE: ShipmentService
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: Amila_Rpw



 