version: "3.8"
services:
  #  api_service:
  #    build: .
  #    image: assignment11/rd:latest
  #    container_name: Assignment11
  #    restart: always
  #    ports:
  #      - 8086:8080
  #    networks:
  #      - springapipostgres-net
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RDCommerce
  #      SPRING_DATASOURCE_USERNAME: postgres
  #      SPRING_DATASOURCE_PASSWORD: Ab123456
  #    depends_on:
  #      - postgres

  discountservice-mysql-write:
    image: "mysql:8.0"
    restart: always
    container_name: DiscountService-MySQL-WriteStorage
    ports:
      - 3301:3306
    environment:
      MYSQL_DATABASE: DiscountService
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: Amila_Rpw