version: "3.7"
services:

  productservice-mysql:
    image: "mysql:8.0"
    restart: always
    container_name: ProductService-MySQL
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: ProductService
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: Amila_Rpw

#  redis:
#    image: "redis:latest"
#    container_name: redis
#    ports:
#      - "6379:6379"

#networks:
#  springapimysql-net:



  #  postgres:
#    image: "postgres:latest"
#    restart: always
#    container_name: postgres-edu
#    ports:
#      - 5420:5432
#    environment:
#      POSTGRES_PASSWORD: Ab123456
#      POSTGRES_USER: postgres
#      POSTGRES_DB: RDCommerce
#networks:
#  springapipostgres-net:

#version: "3.7"
#services:
#  api_service:
#    build: .
#    image: assignment11/rd:latest
#    container_name: Assignment11
#    restart: always
#    ports:
#      - 8086:8080
#    networks:
#      - springapimysql-net
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/marketplace?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: secret
#    depends_on:
#      - mysqldb
#    volumes:
#      - .m2:/root/.m2
#




 