version: "3.8"
services:
  api_service:
    build: .
    image: productservice/ecommerce-microservices:latest
    container_name: ProductService
    restart: always
    ports:
      - 8086:8080
    networks:
      - springapipostgres-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ProductService?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - productservice-mysql
    volumes:
      - .m2:/root/.m2
  productservice-mysql:
    image: "mysql:8.0"
    restart: always
    container_name: ProductService-MySQL
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: ProductService
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: Amila_Rpw