version: "3.9"
services:
  eureka-server:
    build: .
    image: eurekaserver/ecommerce-microservices:latest
    container_name: EurekaServer
    restart: always
    ports:
      - "9999:9999"
    networks:
      - ecommerce-microservices-net

networks:
  ecommerce-microservices-net:
    external: true